server:
  port: 8180
spring:
  application:
    name: mt-core-transfers
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5450/mt_core_transfers
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
    ddl-auto: update
  kafka:
    bootstrap-servers: "localhost:9091"
    producer:
      properties:
        schema.registry.url: http://localhost:8081
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
transfers:
  max-transfer-sum: 100.00
  demo-transfers-enabled: false
  blocked-account-numbers:
    - "123"
    - "234"
    - "456"
integrations:
  limits:
    url: http://localhost:8181/api/v1/limits
    read-timeout: 30s
    write-timeout: 2s
  notifications:
    kafka:
      topics:
        transfer-status: mt.transfers.status.info