server:
  port: 8181
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5450/mt_core_transfers?minimumIdle=2
    username: mt_core_transfers_admin
    password: mt_core_transfers_admin
    hikari:
      minimumIdle: 2
      maximumPoolSize: 4
  jpa:
    show-sql: true
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
integrations:
  limits:
    url: http://localhost:8182/api/v1/limits
    read-timeout: 30s
    write-timeout: 2s
